"""
LLM Bridge — Pydantic data models.

Defines the unified response format, chat parameters, and configuration
schemas used throughout the LLM Bridge module.  Every field exposed to
callers carries a ``Field(description=…)`` so that IDE tooltips and
generated docs are self-documenting.
"""

from __future__ import annotations

from typing import Any, Optional

from pydantic import BaseModel, Field


# ---------------------------------------------------------------------------
# Unified Response
# ---------------------------------------------------------------------------

class UsageInfo(BaseModel):
    """Normalised token-usage counters across all providers.

    Each provider reports token usage differently:
    - **OpenAI**: ``usage.prompt_tokens`` / ``usage.completion_tokens`` / ``usage.total_tokens``
    - **Anthropic**: ``usage.input_tokens`` / ``usage.output_tokens`` (plus optional cache tokens)
    - **Google**: ``usage_metadata.prompt_token_count`` / ``candidates_token_count`` / ``total_token_count``

    This model normalises all of them into a single shape.
    """

    input_tokens: int = Field(
        default=0,
        description="Number of tokens in the input prompt sent to the model.",
    )
    output_tokens: int = Field(
        default=0,
        description="Number of tokens generated by the model in its response.",
    )
    total_tokens: int = Field(
        default=0,
        description="Sum of input_tokens and output_tokens.  For Google models "
        "this may also include thoughts_token_count.",
    )
    cache_creation_input_tokens: int = Field(
        default=0,
        description="(Anthropic only) Tokens used to create a prompt-cache entry.",
    )
    cache_read_input_tokens: int = Field(
        default=0,
        description="(Anthropic only) Tokens read from a prompt-cache entry.",
    )
    reasoning_tokens: int = Field(
        default=0,
        description="(OpenAI o-series / Google thinking) Tokens consumed by "
        "internal chain-of-thought / reasoning.",
    )


class UnifiedResponse(BaseModel):
    """Provider-agnostic response wrapper.

    Every provider adapter MUST return an instance of this model so that
    calling code never needs to know which backend was used.

    Example
    -------
    >>> response = await bridge.chat("openai/gpt-4o", messages=[...])
    >>> print(response.content)       # raw text
    >>> print(response.parsed)        # Pydantic model if response_model was given
    >>> print(response.usage)         # UsageInfo(input_tokens=..., ...)
    >>> print(response.stop_reason)   # "end_turn" / "stop" / "max_tokens" etc.
    """

    provider: str = Field(
        description="Lowercase provider identifier, e.g. 'openai', 'anthropic', 'google'.",
    )
    model: str = Field(
        description="Model name as returned by the provider, e.g. 'gpt-4o', 'claude-sonnet-4'.",
    )
    content: Optional[str] = Field(
        default=None,
        description="Raw text content of the model's response.",
    )
    parsed: Optional[Any] = Field(
        default=None,
        description="Parsed Pydantic model instance when a response_model was supplied.",
    )
    thinking: Optional[str] = Field(
        default=None,
        description="Raw reasoning/thinking process text from the model, if available.",
    )
    usage: UsageInfo = Field(
        default_factory=UsageInfo,
        description="Token consumption breakdown for this request.",
    )
    stop_reason: Optional[str] = Field(
        default=None,
        description="Why the model stopped generating. Provider-specific values: "
        "OpenAI='stop'/'length'/'content_filter'; "
        "Anthropic='end_turn'/'max_tokens'/'stop_sequence'; "
        "Google='STOP'/'MAX_TOKENS'/'SAFETY'.",
    )
    model_id: Optional[str] = Field(
        default=None,
        description="Provider-assigned unique ID for this completion "
        "(e.g. OpenAI 'chatcmpl-…', Anthropic 'msg_…').",
    )


# ---------------------------------------------------------------------------
# Chat Parameters  (passed through LLMBridge.chat → provider adapters)
# ---------------------------------------------------------------------------

class ChatParameters(BaseModel):
    """All optional parameters that can be forwarded to the underlying
    provider SDKs.  Each provider adapter maps these to the correct
    SDK-specific argument names.

    Example
    -------
    >>> params = ChatParameters(temperature=0.2, max_tokens=2048, top_p=0.9)
    >>> response = await bridge.chat("openai/gpt-4o", messages, params=params)
    """

    # --- Generation length ---------------------------------------------------

    max_tokens: Optional[int] = Field(
        default=None,
        description="Maximum number of tokens in the model's response. "
        "**OpenAI** maps this to ``max_completion_tokens`` (the old "
        "``max_tokens`` param is deprecated for o-series models).  "
        "**Anthropic** uses ``max_tokens`` directly — this is REQUIRED "
        "by Anthropic (defaults to 4096 if None).  "
        "**Google** maps this to ``max_output_tokens``.",
    )

    # --- Sampling controls ---------------------------------------------------

    temperature: Optional[float] = Field(
        default=None,
        description="Controls randomness.  Lower = more deterministic.  "
        "**OpenAI**: 0.0–2.0, default 1.0.  "
        "**Anthropic**: 0.0–1.0, default 1.0.  "
        "**Google**: 0.0–2.0, default varies by model.",
    )

    top_p: Optional[float] = Field(
        default=None,
        description="Nucleus sampling — only consider tokens whose cumulative "
        "probability ≤ top_p.  Supported by all three providers.  "
        "Typically use *either* temperature *or* top_p, not both.",
    )

    top_k: Optional[int] = Field(
        default=None,
        description="Only sample from the top K most probable tokens.  "
        "**Anthropic** and **Google** support this natively.  "
        "**OpenAI** does NOT support top_k — it will be silently ignored.",
    )

    # --- Repetition penalties -------------------------------------------------

    frequency_penalty: Optional[float] = Field(
        default=None,
        description="Penalise tokens proportional to how often they already "
        "appeared.  Supported by **OpenAI** (−2.0 to 2.0) and "
        "**Google** (``frequency_penalty``).  Ignored for Anthropic.",
    )

    presence_penalty: Optional[float] = Field(
        default=None,
        description="Flat penalty for tokens that have appeared at least once.  "
        "Supported by **OpenAI** (−2.0 to 2.0) and **Google** "
        "(``presence_penalty``).  Ignored for Anthropic.",
    )

    # --- Stop sequences -------------------------------------------------------

    stop_sequences: Optional[list[str]] = Field(
        default=None,
        description="Custom strings that cause the model to stop generating.  "
        "**OpenAI** maps to ``stop`` (up to 4 sequences).  "
        "**Anthropic** maps to ``stop_sequences``.  "
        "**Google** maps to ``stop_sequences`` in GenerationConfig.",
    )

    # --- Reproducibility ------------------------------------------------------

    seed: Optional[int] = Field(
        default=None,
        description="Deterministic sampling seed.  Supported by **OpenAI** "
        "and **Google**.  Anthropic does NOT support seeds.",
    )

    # --- System prompt --------------------------------------------------------

    system_prompt: Optional[str] = Field(
        default=None,
        description="System-level instruction prepended to the conversation.  "
        "**OpenAI**: injected as a message with role='system'.  "
        "**Anthropic**: passed as the top-level ``system`` parameter.  "
        "**Google**: mapped to ``system_instruction`` in GenerateContentConfig.",
    )


# ---------------------------------------------------------------------------
# Configuration Models  (loaded from YAML)
# ---------------------------------------------------------------------------

class RetryConfig(BaseModel):
    """Retry behaviour settings."""

    max_retries: int = Field(
        default=3,
        description="Max number of retry attempts before raising.",
    )
    base_delay: float = Field(
        default=1.0,
        description="Base delay in seconds before the first retry.",
    )
    max_delay: float = Field(
        default=60.0,
        description="Maximum delay in seconds (caps exponential growth).",
    )
    exponential_base: float = Field(
        default=2.0,
        description="Multiplier applied to the delay after each retry.",
    )


class ModelConfig(BaseModel):
    """Configuration for a single model entry in the YAML config."""

    provider: str = Field(
        description="Provider identifier: 'openai' | 'anthropic' | 'google' | 'vertexai'.",
    )
    model: str = Field(
        description="Model name passed to the SDK, e.g. 'gpt-4o', 'claude-sonnet-4'.",
    )
    api_keys: list[str] = Field(
        default_factory=list,
        description="One or more API keys for round-robin rotation.",
    )
    max_tokens: int = Field(
        default=4096,
        description="Default max output tokens for this model.",
    )
    temperature: float = Field(
        default=0.7,
        description="Default sampling temperature for this model.",
    )
    fallback_models: list[str] = Field(
        default_factory=list,
        description="Ordered list of model aliases to try if this model fails.",
    )
    extra: dict[str, Any] = Field(
        default_factory=dict,
        description="Provider-specific overrides passed as **kwargs to the adapter.",
    )


class BridgeConfig(BaseModel):
    """Top-level config loaded from YAML."""

    models: dict[str, ModelConfig] = Field(
        default_factory=dict,
        description="Mapping of alias → ModelConfig entries.",
    )
    default_model: Optional[str] = Field(
        default=None,
        description="Default model alias used when none is specified.",
    )
    retry: RetryConfig = Field(
        default_factory=RetryConfig,
        description="Global retry settings applied to all calls.",
    )
    log_usage: bool = Field(
        default=True,
        description="Whether to log token usage after each call.",
    )
